name: Easy GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://assorted.downloads.oppo.com/firmware/CPH2015/CPH2015PUEX_11_OTA_0231_all_jCHxG3KuWrOL.ozip 
  ROM_NAME: ColorOS
  ZIP_NAME: test-upload
  erfanrepo: ${{ secrets.ERFANSOURCE }}  
  TZ: Asia/Kolkata
  username : ${{ secrets.UPLOADUSERNAME }}
  password : ${{ secrets.UPLOADPASSWORD }}
  uploadto : uploads.androidfilehost.com
  uploadtype: ftp
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules $erfanrepo
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI 
         run: |
              sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-Aonly.7z *-Aonly-*.img
              curl -T $ZIP_NAME-GSI-Aonly.7z $uploadtype://$username:$password@$uploadto/          
       - name: Zip AB and upload 
         run: |
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-GSI-AB.7z *-AB-*.img
              curl -T $ZIP_NAME-GSI-AB.7z $uploadtype://$username:$password@$uploadto/
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
